apiVersion: v1
kind: Secret
metadata:
  name: notificationsapi-secret
type: Opaque
data:
  # valores em base64 — substituir antes de aplicar em produção
  # echo -n "valor" | base64
  rabbitmq-username: Z3Vlc3Q=
  rabbitmq-password: Z3Vlc3Q=
